<html>

<body>
  <h1>TEACHME</h1>
  <h2> A student-led tutoring organization at SSHL </h2> 
  <p>Welcome to TeachMe!</p>
  <img src="https://content.codecademy.com/articles/github-pages-via-web-app/happy-ice-cream.gif" />
</body>

</html>
